
name: Tests

on: [push]

jobs:

  test-runtime:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # A couple of providers that are 'known good' for testing
        provider: [dnsimple, digitalocean]

    env:
      DNSIMPLE_TEST_DOMAIN: ${{ secrets.DNSIMPLE_TEST_DOMAIN }}
      DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
      DIGITALOCEAN_TEST_DOMAIN: ${{ secrets.DIGITALOCEAN_TEST_DOMAIN }}
      DIGITALOCEAN_API_KEY: ${{ secrets.DIGITALOCEAN_API_KEY }}

    steps:
      
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # Most providers don't handle parallel updates so run everything in series
      - name: Run ${{ matrix.provider }} smol tests
        run: cargo test --features test_${{ matrix.provider }},test_smol -- --test-threads=1

      - name: Run ${{ matrix.provider }} tokio tests
        run: cargo test --features test_${{ matrix.provider }},test_tokio -- --test-threads=1

      - name: Run ${{ matrix.provider }} compio tests
        run: cargo test --features test_${{ matrix.provider }},test_compio -- --test-threads=1

      - name: Run ${{ matrix.provider }} monoio tests
        run: cargo test --features test_${{ matrix.provider }},test_monoio -- --test-threads=1
