
name: Tests

on: [push]

jobs:

  test-runtime:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # DNSMadeEasy's staging servers seem to run legacy SSL which
        # rustls doesn't support, so we don't test here ATM.
        #
        provider: [dnsimple, digitalocean]

    concurrency:
      group: ${{ matrix.provider }}
  
    steps:
      
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run ${{ matrix.provider }} tests
        env:
          DNSIMPLE_TEST_DOMAIN: ${{ secrets.DNSIMPLE_TEST_DOMAIN }}
          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
          DIGITALOCEAN_TEST_DOMAIN: ${{ secrets.DIGITALOCEAN_TEST_DOMAIN }}
          DIGITALOCEAN_API_KEY: ${{ secrets.DIGITALOCEAN_API_KEY }}

        # Most providers don't handle parallel updates so run everything in series
        run: |
          cargo test --features test_${{ matrix.provider }},test_smol -- --test-threads=1
          cargo test --features test_${{ matrix.provider }},test_tokio -- --test-threads=1
          cargo test --features test_${{ matrix.provider }},test_compio -- --test-threads=1
