
name: Tests

on: [push]

jobs:

  test-runtime:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # DNSMadeEasy's staging servers seem to run legacy SSL which
        # rustls doesn't support, so we don't test here ATM.
        #
        # provider: [dnsimple, dnsmadeeasy]
        provider: [dnsimple]

    concurrency:
      group: ${{ matrix.provider }}
  
    steps:
      
      - uses: actions/checkout@v4

      - name: Cache cargo build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Update Rust to latest
        run: rustup update

      - name: Run ${{ matrix.provider }} tests
        env:
          DNSIMPLE_TEST_DOMAIN: ${{ secrets.DNSIMPLE_TEST_DOMAIN }}
          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
          DNSMADEEASY_TEST_DOMAIN: ${{ secrets.DNSMADEEASY_TEST_DOMAIN }}
          DNSMADEEASY_KEY: ${{ secrets.DNSMADEEASY_KEY }}
          DNSMADEEASY_SECRET: ${{ secrets.DNSMADEEASY_SECRET }}

        # Most providers don't handle parallel updates so run everything in series
        run: >
          cargo test --features test_${{ matrix.provider }},test_smol -- --test-threads=1
          &&
          cargo test --features test_${{ matrix.provider }},test_tokio -- --test-threads=1
